version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_PASSWORD: 123
    ports:    
      - 5432:5432
    volumes:
            - postgre_volume:/data/posstgres

  adminer:
        image: adminer
        restart: always
        ports:
                - 8080:8080

  pgadmin:
          image: dpage/pgadmin4:latest
          restart: always
          environment:
                  PGADMIN_DEFAULT_EMAIL: Denis_Sapelnikov200652@mail.ru
                  PGADMIN_DEFAULT_PASSWORD: kdkk2004
                  PGADMIN_LISTEN_PORT: 80
          ports:
                  - 8081:80


volumes:
        postgre_volume:
